//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int Id { get; set; }

        [MaxLength(50), RegularExpression(@"^[A-Z][a-z]*(\s[A-Z][a-z]*)+$", ErrorMessage = "Enter Valid Customer Name"), Required(ErrorMessage = "Please Enter Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter Address")]
        public string Address { get; set; }

        [Display(Name = "Mob No"), RegularExpression(@"^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$", ErrorMessage = "Invalid Phone Number. Please Enter Valid Phone Number."), Required(ErrorMessage = "Please Enter Mobile Number"), StringLength(10, ErrorMessage = "Phone Number Should be 10 Digit long.")]
        public string MobileNo { get; set; }

        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PurchaseItems { get; set; }

        [Display(Name = "Birth Date (MM/dd/yyyy)"), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public DateTime BirthDate { get; set; }

        [Display(Name = "Email ID"), RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Enter Valid Email Id")]
        public string EmailId { get; set; }
    }
}
